### PR TITLE
Work around a stack corruption causing broken GitLab downloads

### LINKED ISSUE #349: Internal server error for projects hosted via gitlab
I am not sure what causes this issue.

Log from command: `dub fetch -v ppc`
```
Using dub registry url 'https://code.dlang.org/'
Refreshing local packages (refresh existing: true)...
Looking for local package map at /var/lib/dub/packages/local-packages.json
Looking for local package map at /home/clipsey/.dub/packages/local-packages.json
Determined package version using GIT: serve-d 0.1.3+commit.7.ga6a358e
Determined package version using GIT: trans-game ~master
Fetching ppc 0.0.2-alpha.2...
Downloading from 'https://code.dlang.org/packages/ppc/0.0.2-alpha.2.zip'
Getting a release version failed: HTTP request returned status code 500 (Internal Server Error)
Retry with ~master...
Fetching ppc ~master...
Downloading from 'https://code.dlang.org/packages/ppc/~master.zip'
HTTP request returned status code 500 (Internal Server Error)
```

### LINKED ISSUE #436: Gitlab dependencies result in server crash
https://code.dlang.org/packages/silly/0.8.2.zip -> directly leads to a server crash (502)

See also: https://code.dlang.org/packages/silly

### PR DESCRIPTION
**Pull request by s-ludwig**
Returning the `Nullable!DbPackage`, implicitly converted to `DbPackage`, triggered a codegen issue on LDC, leading to the version string to become empty on Windows and causing a crash on the following method call on Linux.

Closes #436. Fixes #349.

### CODE REVIEW

File: source/dubregistry/registry.d [hunk 1]
```diff
@@ -388,7 +388,9 @@ class DubRegistry {
 
 	void downloadPackageZip(string packname, string vers, void delegate(scope InputStream) @safe del)
 	{
+		assert(vers.length > 0);
 		DbPackage pack = m_db.getPackage(packname);
+		assert(vers.length > 0);
```
Comment (WebFreak001) [inline source/dubregistry/registry.d]: is it intended that this is 2x the same assert with no changes in value? There is nothing accessing vers there between the 2 calls.

If the stack got corrupted here it could possibly have any value other than 0 too so the assert would probably rarely trigger here. (the `length > 0` is the same as `length != 0` because it's unsigned so it's just checking for only 0) Also it's confusing for future code review why this assert exists 2x

Comment (s-ludwig) [reply source/dubregistry/registry.d]: I agree on it being kind of confusing, maybe I'll just remove it. Of course *anything* can happen, like on Linux, where the symptoms were completely different. Aith the `alias this` for `Nullable.get` being removed soon, this is unlikely to slip back in, so the assertion doesn't have much chance of being an actual help in the future.

**Comment by s-ludwig** [comment]
I've also deployed these changes to code.dlang.org and the gitlab test package now downloads without errors.

**Comment by aliak00** [comment]
Omg why doesn't Nullable just die. Someone kill it with fire!
